### ISSUE TITLE
Config file has nothing in it

### ISSUE THREAD

**Issue by Pigfection** [TalonFloof/EnhancedWeather#38] opened 2024-03-14 10:41 UTC
the config file consists of "{ }" and thats it. Settings dont save between sessions so i get a lil laggy with particle based precipitation.

P.S. if you read this, please make a discord for the mod or smth cause this is sick and im interested to see development updates... 
thank you :)

**Comment by XavierEXE** [comment] 2024-03-14 21:29
I have the same issue, it's a bit annoying having to redo settings each time I open the game. 
I'd also love to see a discord or somewhere to follow development of the mod c:

**Comment by TalonFloof** [comment] 2024-03-15 00:19
Duplicate of #35

**Closed by TalonFloof** 2024-03-15 00:19 UTC
